services:
  bacnet-device:
    image: ${NODE_IMAGE:-node:20}
    working_dir: /bacnet
    volumes:
      - .:/bacnet
    ports:
      - "47808:47808/udp"
    environment:
      - DEBUG=bacstack*
    command: |
      bash -c "npx ts-node emulator/bacnet-device-emulator.ts"
    networks:
      - bacnet-network

  bacnet-client:
    image: ${NODE_IMAGE:-node:20}
    working_dir: /bacnet
    volumes:
      - .:/bacnet
    command: |
      bash -c "tail -f /dev/null"
    networks:
      - bacnet-network

networks:
  bacnet-network:
    driver: bridge