version: '3'
services:
  bacnet-device:
    image: fh1ch/bacstack-compliance-docker
  bacnet-client:
    build:
      context: .
    links:
      - bacnet-device
    volumes:
      - ./reports/coverage:/reports/coverage
