name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        node: [20, 22]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Lint 
        run: npm run lint
      
      - name: Build
        if: matrix.node == '22'
        run: npm run build
    
      - name: Test
        run: |
          NODE_IMAGE=node:${{ matrix.node }} docker compose up -d
          npm run docker:test

      - name: Coveralls
        uses: coverallsapp/github-action@v2.3.4
        if: matrix.node == '20'
        with:
          github-token: ${{ secrets.github_token }}
     # TODO: deploy coverage results
     # - run: yarn integration
     # - run: yarn docs

  # compliance:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - run: docker-compose up --abort-on-container-exit --exit-code-from bacnet-client

  # pages:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-node@v4
  #       with:
  #         node-version: 20
  #         cache: 'yarn'
  #     - run: yarn --frozen-lockfile
  #     - run: yarn docs
      # TODO: deploy pages
